// DUMMY DATA
export const events = [
  {
    id: 1,
    title: 'Sample Event',
    owner: { user_id: 4, name: 'Steve Knobs' },
    activityId: '68c863d3b71fb327abf9ce06',
    brief_description: 'Come join us for a fun game of pickleball!',
    description: 'Pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball longer description',
    additional_info: 'Limited parking available on site. Street parking is recommended.',
    time: '2025-09-29T09:00:00',
    address: '123 Sports Ct, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 2,
    maxPlayers: 8,
    intensityId: '68c88797b71fb327abf9ce08',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://thepickleballprofessionals.com/wp-content/uploads/2024/02/image-4-11.jpg',
  },
  {
    id: 2,
    title: 'Sample Event 2',
    owner: { user_id: 1, name: 'John Sno' },
    activityId: '68cada5727ee75264d4916c4',
    brief_description: 'This is a sample event description for event 2.',
    description: 'Lots of interesting details about this basketball event. All skill levels welcome! Should be a beautiful day to play some hoops outside. Ball is life!',
    additional_info: 'We will be meeting at Court B4.',
    time: '2025-10-19T15:00:00',
    address: '456 Court St, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 4,
    maxPlayers: 10,
    intensityId: '68c88768b71fb327abf9ce07',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://st2.depositphotos.com/1018611/8860/i/950/depositphotos_88608500-stock-photo-teenagers-playing-basketball-game-together.jpg',
  },
];
export const upcomingMyEvents = [
  {
    id: 1,
    title: 'Sample Event',
    owner: { user_id: 4, name: 'Steve Knobs' },
    activityId: '68c863d3b71fb327abf9ce06',
    brief_description: 'Come join us for a fun game of pickleball!',
    description: 'Pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball longer description',
    additional_info: 'Limited parking available on site. Street parking is recommended.',
    time: '2025-09-29T09:00:00',
    address: '123 Sports Ct, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 1, name: 'John Sno' },
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 2,
    maxPlayers: 8,
    intensityId: '68c88797b71fb327abf9ce08',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://thepickleballprofessionals.com/wp-content/uploads/2024/02/image-4-11.jpg',
  },
  {
    id: 2,
    title: 'Sample Event 2',
    owner: { user_id: 1, name: 'John Sno' },
    activityId: '68cada5727ee75264d4916c4',
    brief_description: 'This is a sample event description for event 2.',
    description: 'Lots of interesting details about this basketball event. All skill levels welcome! Should be a beautiful day to play some hoops outside. Ball is life!',
    additional_info: 'We will be meeting at Court B4.',
    time: '2025-10-19T15:00:00',
    address: '456 Court St, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 4,
    maxPlayers: 10,
    intensityId: '68c88768b71fb327abf9ce07',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://st2.depositphotos.com/1018611/8860/i/950/depositphotos_88608500-stock-photo-teenagers-playing-basketball-game-together.jpg',
  },
];
export const pastMyEvents = [
  {
    id: 1,
    title: 'Sample Event',
    owner: { user_id: 4, name: 'Steve Knobs' },
    activityId: '68c863d3b71fb327abf9ce06',
    brief_description: 'Come join us for a fun game of pickleball!',
    description: 'Pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball pickleball longer description',
    additional_info: 'Limited parking available on site. Street parking is recommended.',
    time: '2025-09-09T09:00:00',
    address: '123 Sports Ct, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 1, name: 'John Sno' },
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 2,
    maxPlayers: 8,
    intensityId: '68c88797b71fb327abf9ce08',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://thepickleballprofessionals.com/wp-content/uploads/2024/02/image-4-11.jpg',
  },
  {
    id: 2,
    title: 'Sample Event 2',
    owner: { user_id: 1, name: 'John Sno' },
    activityId: '68cada5727ee75264d4916c4',
    brief_description: 'This is a sample event description for event 2.',
    description: 'Lots of interesting details about this basketball event. All skill levels welcome! Should be a beautiful day to play some hoops outside. Ball is life!',
    additional_info: 'We will be meeting at Court B4.',
    time: '2025-08-19T15:00:00',
    address: '456 Court St, Springfield, USA',
    coordinates: [],
    players: [
      { user_id: 2, name: 'Alice Wonder' },
      { user_id: 3, name: 'Bob Builder', photo: 'https://randomuser.me/api/portraits/men/75.jpg' },
      { user_id: 4, name: 'Steve Knobs' },
    ],
    minPlayers: 4,
    maxPlayers: 10,
    intensityId: '68c88768b71fb327abf9ce07',
    skillId: '68c8632eb71fb327abf9ce02',
    photo: 'https://st2.depositphotos.com/1018611/8860/i/950/depositphotos_88608500-stock-photo-teenagers-playing-basketball-game-together.jpg',
  },
];
